server:
  port: 9090
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m

spring:

  application:
    name: search

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 1
      max-active: 30
      min-idle: 1
      max-wait: 30000

  profiles:
    active: dev

elasticsearch:
  # 协议头
  schema: http
  # 地址
  address: localhost:9200
  # 连接超时
  connectTimeout: 5000
  # socket连接超时
  socketTimeout: 5000
  # 连接请求超时
  connectionRequestTimeout: 5000
  # 最大连接数
  maxConnectNum: 100
  # 最大路由连接数
  maxConnectPerRoute: 100

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.jiachen.datesource.dataobject
